config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :events
  resources :users
  resources :ingredients
  resources :meals
  resources :dishes
  match ':controller(/:action(/:id))', :via => :get

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :user
  belongs_to :meal
  belongs_to :dish
  validates_presence_of :description
  validates_presence_of :amount
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.joins(:user, :meal, :dish).select('meals.id as meal_id,meals.description as meal_description, dishes.description as dish_description, dishes.id as dish_id,users.userName, meals.event_id,users.id as user_id,ingredients.description, ingredients.amount').where('ingredients.id' => params[:id])
    @eventInfo = Event.find(@ingredient[0].event_id)
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:description, :amount, :user_id, :meal_id, :created_by, :created_at, :updated_at, :dish_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    
  </div>
  
  <div class="control-group">
    <%= f.hidden_field :user_id, :class => 'control-label', :value => session[:user_id] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :meal_id, :class => 'control-label', :value => params[:meal] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :created_by, :class => 'control-label', :value => session[:user_id] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :created_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :updated_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :dish_id, :class => 'control-label', :value => params[:dishId] %>
    <div class="controls">
      
    </div>
    
  </div>
  <br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            events_path, :class => 'btn btn-primary' %>
  
 </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ingredients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
      <td><%= ingredient.description %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to @eventInfo.name, event_path(@eventInfo.id) %></h1>
<% @ingredient.each do |i|  %>
<h2><%= i.description %>: <%= i.amount %></h2>
<br/>
Meal: <%= link_to i.meal_description, meal_path(i.meal_id) %>
<br/>
Dish: <%= link_to i.dish_description, dish_path(i.dish_id) %>

<br/>
Owner: <%= link_to i.userName, user_path(i.user_id) %>
<br/>
<% end  %>
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> 
<%= link_to 'Back', ingredients_path %>