config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :events
  resources :users
  resources :ingredients
  resources :meals
  resources :dishes
  match ':controller(/:action(/:id))', :via => :get

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :event
  belongs_to :user
  has_many :ingredient
  has_many :dish
  validates_presence_of :description
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @mealId = params[:id]
    @meal = Meal.joins(:user).select('meals.event_id,meals.description as meal_description').where('meals.id' => params[:id])
    @mealName = Meal.find(params[:id])
    @eventInfo = Event.find(@mealName.event_id)
    @dish = Dish.joins(:user).select('users.userName, users.id as user_id, dishes.description, dishes.id').where('dishes.meal_id' => params[:id])
    @ingredients = Ingredient.joins(:user).select('users.id as user_id, users.userName, ingredients.id, ingredients.description, ingredients.amount, ingredients.dish_id').where('ingredients.meal_id' => params[:id])
  end

  # GET /meals/new
  def new
    @meal = Meal.new

  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      params.require(:meal).permit(:description, :comments, :event_id, :day, :user_id, :created_at, :updated_at)
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<% @eventId = params[:eventId] %>
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    
  </div>
  
  <div class="control-group">
    <%= f.hidden_field :day, :class => 'control-label', :value => params[:day] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :event_id, :class => 'control-label', :value => params[:eventId] %>
    <div class="controls">
     
      
    </div>
    
  </div>
  
<div class="control-group">
    <%= f.hidden_field :user_id, :class => 'control-label', :value => params[:userId] %>
    <div class="controls">
     
     
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :created_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
     
     
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :updated_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
     
     
    </div>
    
  </div>

  <br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            events_path, :class => 'btn btn-primary' %>
  
 
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meals</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to @eventInfo.name, event_path(@eventInfo.id) %></h1>
<h2><%= @mealName.description %> </h2>
<br/>
<button <%='dish_add'%>> <%= link_to "+ Dish", "../dishes/new?meal=" + @mealId + "&eventId=" + @meal[0].event_id.to_s%> </button>
<br/>
<br/>
<table class="table table-striped">
<% @dish.each do |d| %>
	<div class="panel panel-default">
  <div class="panel-heading">
		<h3 class="panel-title"><%= (link_to d.description, dish_path(d.id)) + " - " + d.userName %></h3>
		</div>
	
	<div class="panel-body">
	<% @ingredients.each do |i| %>
	<% if i.dish_id == d.id %>
		<%= link_to i.description + ": " + i.amount, ingredient_path(i.id) %>
		<br/>
		

	<% end %>
	
	<% end %>
	</div>
</div>
	
	
		<br/>
<% end %>



<br/>
<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>