config/routes.rb
Rails.application.routes.draw do
  resources :dishes
  resources :events
  resources :users
  resources :ingredients
  resources :meals
  resources :dishes
  match ':controller(/:action(/:id))', :via => :get

  root 'welcome#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :user
  belongs_to :meal
  belongs_to :event
  has_many :ingredient
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dishId = params[:id]

    @ingredients = Dish.joins(:meal, :user, :ingredient).select('users.userName, dishes.description as dish_description, meals.description as meal_description, ingredients.description as ingredient_description, ingredients.amount, ingredients.id as ingredient_id, meals.event_id').where('dishes.id' => params[:id])

    @dishName = Dish.joins(:meal, :user).select('users.userName, users.id as user_id,dishes.description as dish_description,meals.description as meal_description, meals.event_id,meals.id as meal_id, meals.event_id').where('dishes.id' => params[:id])
    @eventInfo = Event.find(@dishName[0].event_id)
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(dish_params)

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render :show, status: :created, location: @dish }
      else
        format.html { render :new }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    respond_to do |format|
      if @dish.update(dish_params)
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { render :show, status: :ok, location: @dish }
      else
        format.html { render :edit }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish.destroy
    respond_to do |format|
      format.html { redirect_to dishes_url, notice: 'Dish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:description, :user_id, :meal_id, :event_id)
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_form.html.erb
<%= form_for(@dish) do |f| %>
  <% if @dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% @dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    
  </div>
  
  <div class="control-group">
    <%= f.hidden_field :user_id, :class => 'control-label', :value => session[:user_id] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :meal_id, :class => 'control-label', :value => params[:meal] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :event_id, :class => 'control-label', :value => params[:eventId] %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :created_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
      
    </div>
    
  </div>
  <div class="control-group">
    <%= f.hidden_field :updated_at, :class => 'control-label', :value => Date.today.to_s %>
    <div class="controls">
      
    </div>
    
  
   

  <br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            events_path, :class => 'btn btn-primary' %>
  
 
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dishes</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th>Meal</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dishes.each do |dish| %>
      <tr>
        <td><%= dish.description %></td>
        <td><%= dish.user %></td>
        <td><%= dish.meal %></td>
        <td><%= dish.event %></td>
        <td><%= link_to 'Show', dish %></td>
        <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
        <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= link_to @eventInfo.name, event_path(@eventInfo.id)%></h1>
<br/>
<button <%='name="ingredient_add"'%>> <%= link_to "+ Ingredient", "../ingredients/new?meal=" + @dishName[0].meal_id.to_s + "&dishId=" + @dishId.to_s%> </button>
<br/>
<br/>


<% @dishName.each do |dn| %>
	<h2><%= dn.dish_description %></h2>
	<br/>
	Meal: <%= link_to dn.meal_description, meal_path(dn.meal_id) %>
	<br/>
	Owner: <%= link_to dn.userName, user_path(dn.user_id) %>
	<br/>
	Ingredients:
	<br/>
<% end %>
<% @ingredients.each do |d| %>
	<%= link_to d.ingredient_description + ": " + d.amount, ingredient_path(d.ingredient_id) %>
	<br/>
	


<% end %>

<br/>
<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>